### ISSUE TITLE
[bug] Firebase dependency issue

### ISSUE THREAD

**Issue by yashmurty** [mamori-i-japan/mamori-i-japan-api#76]
I saw this strange error in the logs.
We might face this sooner or later.
We can investigate this later if we run in to it quite often. :pray: 
```
2020-04-24T11:23:48.889Z	690de5f8-b3e5-4b4f-b238-0af7bf0c6d13	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "14 UNAVAILABLE: No connection established",
    "code": 14,
    "details": "No connection established",
    "metadata": {
        "internalRepr": {},
        "options": {}
    },
    "stack": [
        "Error: 14 UNAVAILABLE: No connection established",
        "    at Object.callErrorFromStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call.js:30:26)",
        "    at Object.onReceiveStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/client.js:327:49)",
        "    at Object.onReceiveStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)",
        "    at Http2CallStream.outputStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)",
        "    at Http2CallStream.maybeOutputStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)",
        "    at Http2CallStream.endCall (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)",
        "    at Http2CallStream.cancelWithStatus (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)",
        "    at ChannelImplementation.tryPick (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/channel.js:214:32)",
        "    at ChannelImplementation._startCallStream (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/channel.js:244:14)",
        "    at Http2CallStream.start (/opt/nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:418:22)"
    ]
}
```

Found these related issues on github.
https://github.com/grpc/grpc-node/issues/1064
https://github.com/googleapis/nodejs-pubsub/issues/890

**Comment by ambativamsi** [comment]
same issue for me!!

**Comment by vamsiambati** [comment]
Looks like this is internet issue...in my case after changing the isp solved this
